### ISSUE TITLE
Add link to reach official documentation

### ISSUE THREAD

**Issue by manueljordan** [gnome-terminator/gnome-terminator.github.io#33]
Hello 

The [https://gnome-terminator.org](https://gnome-terminator.org) page does not have a link to reach the official documentation page. I am not sure which one would be added:

* [https://gnome-terminator.readthedocs.io/en/latest/](https://gnome-terminator.readthedocs.io/en/latest/)
* [https://terminator-gtk3.readthedocs.io/en/latest/](https://terminator-gtk3.readthedocs.io/en/latest/)

Thanks for your understanding.

**Comment by mattrose** [comment]
I don't know what the source is for https://terminator-gtk3.readthedocs.io/en/latest/ so I'm definitely going to say that the official docs are at https://gnome-terminator.readthedocs.io/en/latest/ and the sources are at https://github.com/gnome-terminator/docs I added a link to the docs in PR #34

**Comment by manueljordan** [comment]
Thanks for the quick feedback, I don't want be rude, but consider to add the link at the top menu of the page, I mean, together with `About` and `Overview`. It is more direct than in the `Relevant Links` section of the `About` page. Of course, it can be keep it.

Thanks for you understanding

**Comment by mattrose** [comment]
You're right of course, but honestly, I'm just not sure how to change the top bar on the website to make a link to an external resource rather than a page.  I'll play a little bit, or if you have an idea how to do it, you could make a PR.
